### ISSUE TITLE
Your submission title

### ISSUE THREAD

**Issue by riccardoporreca** [riccardoporreca/test-github-community#5]
Submit your contributions by filling the following information

``` yaml
# Contribution's title and author.
title: An Awesome COVID-19 Contribution
author: The Autor
# Short title to be used in the website Gallery menu
menu_entry: Short title
# URL of the public source code repository
repository: https://github.com/user/repo
# The type of contribution and how it can be featured as gallery content.
# For a shiny app:
type: shiny
content: URL of the your shiny web app, e.g. https://user.shinyapps.io/my-app
# Any online published resource (e.g. a website / report):
type: webpage
content: URL of the webpage, e.g. https://user.github.io/my-analysis
# For more complex / heterogeneous contributions, you can create a GitHub
# Gist (https://gist.github.com/) with the relevant information and pointers
type: gist
content: <script...> # you can place here what you get from the "Embed" button
```

In addition:

- [ ] Send an email to covidrcontest@erum.io (for further direct communication down the road)
     - Subject: "Submission to CovidR: Issue #00", where #00 is the number of this Issue
     - Content: A full link to this Issue
     
If you have questions specific to your submission, used the comments in this Issue.
